updated gltf importer
BRL-CAD/brlcad pull request #10
Opened 2021-12-11 04:39 UTC by volivarez60

2021-12-15 20:23 UTC, brlcad requested changes
Hi @volivarez60 this commit looks like a mistake or change from earlier.  Can you undo it?  Doesn't look like you submitted a src/libgcv/plugins/gltf plugin so this commit will break the build.

2021-12-15 20:26 UTC, brlcad requested changes
@volivarez60 It's probably because you pulled tinygltf from git already. Try deleting the tinygltf/.git folder, then git add src/conv/gltf/tinygltf.  If you do that, you should be able to commit and the PR can be updated with the necessary files.

2021-12-15 22:46 UTC, brlcad approved these changes

2021-12-16 18:18 UTC, starseeker commented
A thought - can the tinygltf contents be stripped down to a minimum?  (I.e., something like LICENSE, tiny_gltf.* and stb_image* files?)

2021-12-16 18:20 UTC, starseeker commented
The examples folder in particular is 23M, and models and tests together add another 1.4M

2021-12-16 18:27 UTC, volivarez60 commented
Yeah I could get rid of them most likely, I can fix that probably Saturday because im out of town until then.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Clifford Yapp ***@***.***>
Sent: Thursday, December 16, 2021 12:21:00 PM
To: BRL-CAD/brlcad ***@***.***>
Cc: volivarez60 ***@***.***>; Mention ***@***.***>
Subject: Re: [BRL-CAD/brlcad] updated gltf importer (PR #10)


The examples folder in particular is 23M, and models and tests together add another 1.4M

—
Reply to this email directly, view it on GitHub<https://github.com/BRL-CAD/brlcad/pull/10#issuecomment-996065690>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANYNKTKBZ7GWPZHBT57WXDDURIUYZANCNFSM5J2R4JMQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-02-23 15:57 UTC, merged